steps:
  - label: 'run the cardano node sync test on Mainnet using a Linux machine'
    commands:
      - nix-shell --run 'python ./sync_tests/sync_test.py -t1 $tag_no1 -t2 $tag_no2 -e "mainnet"'
      - './.buildkite/sync_tests_pull.sh'
      - nix-shell --run 'python ./sync_tests/write_values_to_db.py -e "mainnet"'
      - './.buildkite/sync_tests_push.sh'
    branches: "dorin/*"
    timeout_in_minutes: 1200
    agents:
      system: x86_64-linux
      queue: benchmark
    artifact_paths:
      - 'logfile.log'
  - label: 'run the db-sync sync tests on Mainnet using a Linux machine'
    if: "$dt_tag_no1 != None"
    commands:
      - './.buildkite/sync_db_sync.sh'
      - nix-shell --run 'python ./sync_tests/db_sync_test.py -dt1 $dt_tag_no1 -dt2 $dt_tag_no2'
    branches: "dorin/*"
    timeout_in_minutes: 1200
    agents:
      system: x86_64-linux
      queue: benchmark
    artifact_paths:
      - 'logfile.log'
